# Numpy

In [1]:
import numpy as np

In [2]:
ar = np.array([3,6,7])      #one-dimensional array

In [3]:
ar

array([3, 6, 7])

In [4]:
ar2 = np.array([[1,3,5], [2,4,6]])     #two-dimensional array

In [5]:
ar2

array([[1, 3, 5],
       [2, 4, 6]])

In [6]:
ar2.shape        #shape of the array

(2, 3)

In [7]:
ar3 = ar2.reshape(3,2)       #to change the shape of array

In [8]:
ar3

array([[1, 3],
       [5, 2],
       [4, 6]])

In [9]:
ar3.shape

(3, 2)

In [10]:
print("Rank of array ar3: ", ar3.ndim)
print("Total number of elements in the array ar3: ", ar3.size)
print("Data type of the elements of array ar3:", ar3.dtype)

Rank of array ar3:  2
Total number of elements in the array ar3:  6
Data type of the elements of array ar3: int32


In [11]:
ar3[0,1]         #Accessing the element of array using row and column index

3

In [12]:
ar2[1,2]

6

In [13]:
np.arange(15)      #integers from 0 to 14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(1,16,2)     #integers from 1 to 15 with step size of 2

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [15]:
np.zeros((2,2))      #2*2 matrix of 0s

array([[0., 0.],
       [0., 0.]])

In [16]:
np.ones((3,3))      #3*3 matrix of 1s

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(1,6,4)     #4 linearly spaced values from 1 to 6

array([1.        , 2.66666667, 4.33333333, 6.        ])

In [18]:
a = np.array([0,30,45,60,90])
np.sin(a*np.pi/180)               #value of sine function at different angles

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [19]:
r1 = np.random.rand(3,4)      #array of random numbers
r1

array([[0.44496923, 0.05005366, 0.27522664, 0.98676416],
       [0.1698861 , 0.4147249 , 0.04969672, 0.17029719],
       [0.61580128, 0.23779923, 0.88256914, 0.81357524]])

In [20]:
r2 = np.random.randn(2,3)       #array of random numbers from normal distribution
r2

array([[-2.22741491,  2.32403209, -2.1309468 ],
       [ 0.34107847, -0.61753927,  0.60733588]])

In [21]:
r3 = np.random.randint(1,51,10)   #10 random integer between 1 and 50
r3

array([43, 37, 45, 14,  4, 17, 26, 30, 28, 17])

In [22]:
r3.max()

45

In [23]:
r3.min()

4

In [24]:
print(r1.mean())           #Mean of array
print(r1.mean(axis=0))     #Column-wise mean
print(r1.mean(axis=1))     #Row-wise mean

0.42594695716712927
[0.41021887 0.2341926  0.4024975  0.65687886]
[0.43925342 0.20115123 0.63743622]


In [25]:
print(r1.std())           #Standard deviation of array
print(r1.std(axis=0))     #Column-wise standard deviation
print(r1.std(axis=1))     #Row-wise standard deviation

0.3138083339786943
[0.183695   0.14889825 0.35172671 0.35125479]
[0.3457535  0.13274191 0.25064562]


In [26]:
X = np.array([[4,6,2],[1,6,9]])
X

array([[4, 6, 2],
       [1, 6, 9]])

In [27]:
Y = X      #Shallow copy

In [28]:
Y[1,2] = 7   #Changes made to Y will reflect in X

In [29]:
X

array([[4, 6, 2],
       [1, 6, 7]])

In [30]:
Z = X.copy()     #Deep copy

In [31]:
Z[0,1] = 3

In [32]:
Z

array([[4, 3, 2],
       [1, 6, 7]])

In [33]:
X            #Changes made to Z do not reflect in X

array([[4, 6, 2],
       [1, 6, 7]])